name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  gh-pages-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask==2.0.1 Werkzeug==2.0.3 Frozen-Flask==0.18 PyYAML==5.4.1 Jinja2>=3.0.1

      - name: Build static site
        run: |
          cd src/tag-generator
          # Crear estructura de directorios y archivos estáticos
          mkdir -p static/css static/js
          cp -r static/* build/static/ || true
          python freeze.py
          # Asegurar que los archivos estáticos estén en el build
          mkdir -p build/static/{css,js}
          touch build/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/tag-generator/build

  gh-pages-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: gh-pages-build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
