name: Generate README

on:
  push:
    branches: [ main ]
    paths:
      - 'scripts/generate_readme.py'
      - 'scripts/README_TEMPLATE.md'
      - 'tags.yml'

  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]
    paths:
      - 'scripts/generate_readme.py'
      - 'scripts/README_TEMPLATE.md'
      - 'tags.yml'

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone to improve speed

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: requirements.txt

      # Generate README
      - name: Generate README
        run: |
          python scripts/generate_readme.py

      # Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-generate README [skip ci]" || echo "No changes to commit"
          git push origin HEAD

      # Add README to Summary
      - name: Add README to Summary
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const readme = fs.readFileSync('README.md', 'utf8');
            await core.summary
              .addHeading('Generated README')
              .addRaw(readme)
              .write();

