name: Tag Guardian Report

on:
  push:
    branches: [ main ]
    paths:
      - '**.csv'
      - 'tags.yml'
      - 'scripts/tag_guardian.py'
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]
    paths:
      - '**.csv'
      - 'tags.yml'
      - 'scripts/tag_guardian.py'

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyyaml
          
      - name: Run Tag Guardian
        run: |
          python scripts/tag_guardian.py
          
      - name: Add Main Report to Summary
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('tag_guardian_report.md', 'utf8');
            await core.summary
              .addHeading('Tag Guardian Validation Report')
              .addRaw(report)
              .write();
            
            // Add each file report to separate sections
            const reportsDir = 'reports';
            if (fs.existsSync(reportsDir)) {
              const files = fs.readdirSync(reportsDir);
              for (const file of files) {
                const content = fs.readFileSync(`${reportsDir}/${file}`, 'utf8');
                await core.summary
                  .addSeparator()
                  .addRaw(content)
                  .write();
              }
            }

      - name: Upload All Reports
        uses: actions/upload-artifact@v4
        with:
          name: tag-guardian-reports
          path: |
            tag_guardian_report.md
            reports/*.md
