name: Tag Guardian Report

on:
  push:
    paths:
      - '**.csv'
      - 'tags.yml'
      - 'scripts/tag_guardian.py'
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]
    paths:
      - '**.csv'
      - 'tags.yml'
      - 'scripts/tag_guardian.py'

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyyaml
          
      - name: Run Tag Guardian
        run: |
          python scripts/tag_guardian.py
          
      - name: Add Report to Job Summary
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('tag_validation_report.md', 'utf8');
            core.summary
              .addHeading('Tag Guardian Validation Report')
              .addRaw(report)
              .write();
