name: Tag Guardian Report

on:
  push:
    branches: [ main ]
    paths:
      - '**.csv'
      - 'tags.yml'
      - 'scripts/tag_guardian.py'
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]
    paths:
      - '**.csv'
      - 'tags.yml'
      - 'scripts/tag_guardian.py'

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone to improve the speed
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: requirements.txt
          
      - name: Get pip cache dir
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
          
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      - name: Install dependencies
        run: pip install -r requirements.txt
          
      - name: Run Tag Guardian
        run: |
          python -m scripts.tag_guardian
          
      - name: Add Main Report to Summary
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('tag_guardian_report.md', 'utf8');
            await core.summary
              .addHeading('Tag Guardian Validation Report')
              .addRaw(report)
              .write();

      - name: Upload All Reports
        uses: actions/upload-artifact@v4
        with:
          name: tag-guardian-reports
          path: |
            tag_guardian_report.md
            reports/
